version: '3.8'

services:
  apache:
    build:
      dockerfile: docker/apache/Dockerfile
    restart: always
    environment:
      - APP_CONTAINER=symfony_app
      - SERVER_NAME=card.localhost
    networks:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:rw
      - ./docker/apache/apache2.conf:/usr/local/apache2/conf/extra/conf/proshop.conf:ro
      - ./docker/apache/apache-vhosts.conf:/usr/local/apache2/conf/extra/vhost/base-vhost.conf:ro
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    networks:
      - frontend
      - backend
    restart: always
    volumes:
      - ./:/var/www/html:rw
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://db_user:db_password@db_host:3306/db_name
    depends_on:
      - db
      - apache
  db:
    image: mysql:5.7
    container_name: symfony_db
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  frontend:
  backend: